language: node_js
before_install:
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update -qq
  - sudo apt-get install -y php5 php5-cli
  - npm install
  - npm install -g mocha
  - npm install bin-check
node_js:
  - stable
  - 4.2
  - 0.10
  - 0.12
scripts: {
  "test": "./node_modules/mocha/bin/mocha"
}
